server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: TailorService
          uri: http://localhost:8085
          predicates:
            - Path=/tailors/**
        - id: OrderService
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**
        - id: UserService
          uri: http://localhost:8082
          predicates:
            - Path=/users/**
        - id: measurementService
          uri: http://localhost:8083
          predicates:
            - Path=/measurements/**